### PR TITLE
Bumped dependencies

### PR DESCRIPTION
**Pull request by droidjavier**
Bumped dependencies used by the project. No breaking changes whatsoever, tests still pass.

### CODE REVIEW

**Comment by droidjavier** [comment]
I see Travis fails because it's trying to execute `dartanalyzer true`? No dart files found at: /home/javier/github/eosdart/true :D

**Comment by fzxu** [comment]
Thanks for the PR. it seems there is conflict as well as failed build.

**Comment by droidjavier** [comment]
Can you verify the CI is doing the dartanalyzer properly? I run `dartanalyzer .` on my end and it finds no issues. However, Travis is trying to run `dartanalyzer true` 🤷‍♂️
```
$ dartanalyzer true
Analyzing true...
No dart files found at: /home/travis/build/primes-network/eosdart/true
```

**Review by fzxu — APPROVED** [review]

**Comment by fzxu** [comment]
could you rebase the PR against the master? I've fixed the build in master.

**Comment by fzxu** [comment]
@javierjmc ping

**Comment by droidjavier** [comment]
@fzxu rebased

**Pull request merged**
