### PR TITLE
support abi float32 and float64 types

### PR DESCRIPTION
**Pull request by poi5305**

### CODE REVIEW

**Comment by fzxu** [comment]
@poi5305 was it tested?

**Comment by droidjavier** [comment]
I tested this to get the eosio contract abi which contains both `float32` and `float64` and it worked just fine.

**Comment by fzxu** [comment]
it seems the build failed...

**Comment by droidjavier** [comment]
@poi5305 do you mind formatting `lib/src/serialize.dart` with dartfmt?

**Comment by fzxu** [comment]
@poi5305 could you also rebase to the current master? thx!

**Comment by poi5305** [comment]
sure. I have updated the merge request.

**Comment by fzxu** [comment]
Thanks @poi5305 !

**Pull request merged**
