### PR TITLE
Migrates to null safety.

### PR DESCRIPTION
**Pull request by xuelongqy**

### CODE REVIEW

**Comment by fzxu** [comment]
@xuelongqy  Thanks for the PR. It seems there is no Check build run. Do you know why?

**Comment by fzxu** [comment]
it seems the CI build failed... @xuelongqy

**Comment by xuelongqy** [comment]
> it seems the CI build failed... @xuelongqy

Fixed "test Dart". But "Task Dart": dartfmt: command not found

**Comment by xuelongqy** [comment]
it looks ok @fzxu

**Comment by fzxu** [comment]
nice Thanks @xuelongqy

**Pull request merged**
